repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        language: python
        verbose: true
        entry: bash -c 'mypy --strict src/ || true' --
      - id: pylint
        name: pylint
        language: python
        verbose: true
        entry: bash -c 'pylint src/ || true' --
      - id: black
        name: black
        language: python
        verbose: true
        entry: bash -c 'black --diff src/ || true' --
